export const SHOW_HIDE_NAVBAR = 'SHOW_HIDE_NAVBAR';
export const SHOW_HIDE_NAVBAR_TOP = 'SHOW_HIDE_NAVBAR_TOP';
export const RECV_JSON_ERROR = 'RECV_JSON_ERROR';
export const REQ_JSON_DATA = 'REQ_JSON_DATA';
export const RECV_JSON_DATA = 'RECV_JSON_DATA';
